= PatientBook - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/CS2103-AY1819S1-T12-2/main

By: `Team T12-2`      Since: `Jun 2016`      Licence: `MIT`
[[Features]]
== Features

====
*Command Format*

.   Commands are, in general, case sensitive.
.   Words in `UPPER_CASE` are parameters to be supplied by the user, eg. in `add patient n/NAME`, `NAME` is a parameter which can be used as `add n/John Doe`.
.   Items in square brackets are optional. +
    e.g. `make appointment [at 3pm] [next week]` may be entered as `make appointment`, and the program will prompt for the details as required.
.   Parameters may be specified in any order, eg. `make appointment next week at 3pm` is also acceptable for the abovementioned command.
====

[NOTE]
In some places in this guide, you will find that two or more commands have been placed within curly brackets and separated by forward-slashes. This indicates that the commands are equivalent. For example, `{schedule/make} appointment` indicates that `schedule appointment` and `make appointment` are both equally valid.

=== View help : `help`

*Format:* `help`

Opens this user guide to display information on how to use PatientBook. Help command works in both patient management
mode and appointment management mode.

=== Switch to patient management mode : `mode patient`

*Format:* `mode patient`

Switches the application to patient management mode. In this mode, you can view and manage patients’ data. When you
enter a valid command regarding patient in appointment management mode, the application will switch to patient management
mode automatically.

=== Switch to appointment management mode : `mode appointment`

*Format:* `mode appointment`

Switches the application to appointment management mode. In this mode, you can view and manage your patient's appointments.
When you enter a valid command regarding appointment in patient management mode, the application will switch to
appointment management mode automatically.

=== List entered commands : `history`

*Format:* `history`

Lists all commands that you have entered in reverse chronological order.

[TIP]
Tip: Pressing up and down arrows will display the previous and next input respectively in the command box.

=== Exit the program : `exit`

*Format:* `exit`

Exits the program.

== Command Summary

* *Add A Disease* :

* *Add A Patient* : `add patient` +

* *Add An Appointment* : `add appointment` +

* *Clear All Appointments* : `clear`

* *Delete A Patient Record (Mark As Absent)* : `delete patient`

* *Delete An Appointment* : `delete appointment`

* *Edit Appointment Information* : `edit appointment`

* *Edit Patient Information* : `edit patient` +

* *Exit The Program* : `exit`

* *List All Appointments* : `list appointments` +

* *List All Diseases* :

* *List All Patients* : `list patients` +

* *View Command History* : `history`

* *Locate An Appointment* : `find appointment`

* *Locate Diseases* :

* *Locate Patients By Name* : `find patient`

* *Predict Disease* :

* *Switch To Appointment Management Mode* : `mode appointment` +

* *Switch To Patient Management Mode:* : `mode patient` +

* *View Help* : `help` +
